import { useState, type FormEvent } from 'react'
import { ArrowRight, Check, Eye, EyeOff, X } from 'lucide-react'
import { api } from './api'

type Props = { mode: 'login' | 'signup'; onBack: () => void; onSwitch: (mode: 'login' | 'signup') => void; onSuccess?: () => void }
const rules = [{ label: 'At least 8 characters', test: (value: string) => value.length >= 8 }, { label: 'One uppercase letter', test: (value: string) => /[A-Z]/.test(value) }, { label: 'One lowercase letter', test: (value: string) => /[a-z]/.test(value) }, { label: 'One number', test: (value: string) => /\d/.test(value) }, { label: 'One special character', test: (value: string) => /[^A-Za-z0-9]/.test(value) }]
function CodeEditor() { return <div className="auth-editor" aria-label="Animated API request editor"><div className="editor-bar"><span className="editor-dots">● ● ●</span><span>request.api</span><span className="editor-status">● running</span></div><div className="editor-body"><div className="editor-gutter">01<br/>02<br/>03<br/>04<br/>05<br/>06<br/>07<br/>08</div><div className="editor-code"><div className="code-line code-get"><b>GET</b> <span>/users</span></div><div className="code-line code-post"><b>POST</b> <span>/collections</span></div><div className="code-line code-put"><b>PUT</b> <span>/users/:id</span></div><div className="code-line code-delete"><b>DELETE</b> <span>/users/:id</span></div><div className="code-divider"/><div className="code-response"><small>RESPONSE</small><strong>200 OK</strong><span>184 ms</span></div><div className="code-json"><i>{'{'}</i><span> "data": [ ... ]</span><i>{'}'}</i></div></div></div></div> }

export function ConnectedAuth({ mode, onBack, onSwitch, onSuccess }: Props) {
  const signup = mode === 'signup'; const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [password, setPassword] = useState(''); const [emailError, setEmailError] = useState(''); const [showPassword, setShowPassword] = useState(false)
  const validateEmail = (value: string) => { if (value && !value.includes('@')) setEmailError('Enter a valid email address containing @.'); else setEmailError(''); return !value || value.includes('@') }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const email = String(data.get('email') || ''); if (!validateEmail(email)) return; setLoading(true); setError(''); const passwordValue = String(data.get('password') || ''); try { if (signup) { await api.auth.register({ email, username: String(data.get('username') || ''), password: passwordValue }); onSwitch('login') } else { const tokens = await api.auth.login({ email, password: passwordValue }); localStorage.setItem('api_studio_access_token', tokens.access_token); localStorage.setItem('api_studio_refresh_token', tokens.refresh_token); onSuccess?.(); window.location.reload() } } catch (err) { setError(err instanceof Error ? err.message : 'Unable to complete authentication.') } finally { setLoading(false) } }
  return <div className="auth-page"><section className="auth-context"><button className="brand auth-brand" onClick={onBack}><span className="brand-mark">A</span><span>API Studio</span><span className="brand-ai">AI</span></button><div className="auth-message"><span className="eyebrow">A clearer API workflow</span><h1>{signup ? 'Start with the request.' : 'Welcome back to the workbench.'}</h1><p>{signup ? 'Build, inspect, and understand every request in one focused workspace.' : 'Your collections, environments, and request history are ready when you are.'}</p></div><CodeEditor/><button className="auth-back" onClick={onBack}>← Back to overview</button></section><section className="auth-form-side"><div className="auth-form"><div className="auth-form-heading"><span className="eyebrow">{signup ? 'Create account' : 'Sign in'}</span><h2>{signup ? 'Build with clarity.' : 'Good to see you.'}</h2><p>{signup ? 'Create your workspace and make your next request easier to understand.' : 'Continue to your API workspace.'}</p></div><form onSubmit={submit}>{signup && <label>Username<input name="username" required minLength={3} maxLength={30} placeholder="ada_lovelace" /></label>}<label>Work email<input name="email" required type="email" placeholder="you@company.com" onBlur={event => validateEmail(event.target.value)} />{emailError && <span className="field-error">{emailError}</span>}</label><label>Password<div className="password-input"><input name="password" required minLength={8} type={showPassword ? 'text' : 'password'} placeholder="At least 8 characters" onChange={event => setPassword(event.target.value)} /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(value => !value)}>{showPassword ? <EyeOff size={16}/> : <Eye size={16}/>}</button></div></label>{signup && <div className="password-rules" aria-live="polite">{rules.map(rule => { const valid = rule.test(password); return <div key={rule.label} className={valid ? 'valid' : ''}>{valid ? <Check size={14}/> : <X size={14}/>}<span>{rule.label}</span></div> })}</div>}{signup && <label className="check-label"><input required type="checkbox"/> <span>I agree to the terms and privacy policy.</span></label>}{error && <div className="auth-error" role="alert">{error}</div>}<button disabled={loading} className="primary-button auth-submit">{loading ? 'Working…' : signup ? 'Create workspace' : 'Log in'} {!loading && <ArrowRight size={15}/>}</button></form>{!signup && <button className="forgot">Forgot your password?</button>}<div className="auth-switch">{signup ? 'Already have an account?' : 'New to API Studio AI?'} <button onClick={() => onSwitch(signup ? 'login' : 'signup')}>{signup ? 'Log in' : 'Sign up free'}</button></div></div></section></div>
}
