import { useEffect, useState, type MouseEvent } from 'react'
import { createRoot } from 'react-dom/client'
import { Bot, ChevronDown, Clock3, Code2, Folder, History, Plus, Send, Settings, Sparkles, X, ArrowRight, Check, Upload, Terminal, ShieldCheck, Menu } from 'lucide-react'
import DashboardConnected from './DashboardConnected'
import '../styles.css'
import './landing.css'
import './refinements.css'
import './landing-light.css'
import './landing-content.css'
import './api-visual.css'
import './final-image-fix.css'
import './send-button-clean.css'
import './dashboard-flat.css'
import './semantic-syntax.css'
import './request-editor.css'
import './topbar-refinement.css'
import './proof-motion.css'
import './proof-style.css'
import './auth.css'
import './auth-error.css'
import './auth-refinement.css'
import './auth-artwork.css'
import './auth-motion.css'
import './auth-layout-fix.css'
import './auth-editor.css'
import './forge-brand.css'
import './forge-footer.css'
import './forge-auth-brand.css'
import './sticky-nav.css'
import './landing-dots.css'
import './dashboard-theme.css'
import './dashboard-header-fix.css'
import './dashboard-scroll.css'
import './theme-toggle.css'
import './new-request-light.css'
import './sticky-nav-top.css'
import './landing-rhythm.css'
import './auth-fields.css'
import './password-rules.css'
import './username-field.css'
import './auth-transition.css'
import './auth-inputs.css'
import './auth-form-transition.css'
import { api } from './api'
import { ConnectedAuth as Auth } from './ConnectedAuth'
import './scroll-motion.css'

const nav = [{ label: 'Collections', icon: Folder }, { label: 'Environments', icon: Code2 }, { label: 'History', icon: History }, { label: 'AI assistant', icon: Sparkles }]
const tabs = ['Params', 'Authorization', 'Headers', 'Body', 'Scripts', 'Settings']

function LegacyWorkspace() {
  const [url, setUrl] = useState('https://api.example.com/users')
  const [sent, setSent] = useState(false)
  const [activeNav, setActiveNav] = useState('Collections')
  const [activeTab, setActiveTab] = useState('Params')
  const [lightTheme, setLightTheme] = useState(true)
  const send = () => setSent(true)
  const reset = () => { setUrl(''); setSent(false) }
  const logout = () => { localStorage.removeItem('api_studio_access_token'); localStorage.removeItem('api_studio_refresh_token'); window.location.reload() }
  useEffect(() => { const actions = document.querySelector('.workspace-app .top-actions'); if (!actions) return; const theme = document.createElement('button'); theme.className = 'theme-toggle'; theme.textContent = lightTheme ? '☾' : '☀'; theme.title = lightTheme ? 'Switch to dark theme' : 'Switch to light theme'; theme.setAttribute('aria-label', theme.title); theme.onclick = () => setLightTheme(value => !value); const out = document.createElement('button'); out.className = 'logout-button'; out.textContent = 'Log out'; out.onclick = logout; actions.prepend(theme); actions.prepend(out); return () => { theme.remove(); out.remove() } }, [lightTheme])
  return <div className={`app-shell workspace-app ${lightTheme ? 'light-theme' : ''}`}>
    <header className="topbar"><div className="brand"><span className="brand-mark">A</span><span>API Studio</span><span className="brand-ai">AI</span></div><button className="workspace-switcher">Personal workspace <ChevronDown size={14}/></button><div className="top-actions"><button className="quiet-button">⌘ K</button><button className="icon-button" aria-label="Notifications"><Clock3 size={16}/></button><button className="avatar">V</button></div></header>
    <div className="workspace"><aside className="rail"><button className="new-request" onClick={reset}><Plus size={17}/> New request <kbd>⌘ N</kbd></button><nav>{nav.map(({ label, icon: Icon }) => <button key={label} className={`nav-item ${activeNav === label ? 'active' : ''}`} onClick={() => setActiveNav(label)}><Icon size={16}/>{label}</button>)}</nav><div className="rail-bottom"><button className="nav-item"><Settings size={16}/>Settings</button></div></aside>
      <main className="main-panel"><div className="request-tabs"><button className="request-tab active">Untitled request <X size={13}/></button><button className="add-tab" onClick={reset}><Plus size={16}/></button></div><section className="builder"><div className="builder-toolbar"><div className="crumb">Workspace <span>/</span> New request</div><div className="toolbar-actions"><button className="quiet-button">Import cURL</button><button className="quiet-button"><Sparkles size={14}/> AI Generate</button><button className="primary-button" onClick={send}><Send size={14}/>Send <kbd>⌘ ↵</kbd></button></div></div><div className="request-line"><select aria-label="HTTP method"><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select><input value={url} onChange={e => setUrl(e.target.value)} aria-label="Request URL" placeholder="https://"/><button className="save-button">Save</button></div><div className="section-tabs">{tabs.map(tab => <button key={tab} className={`section-tab ${activeTab === tab ? 'active' : ''}`} onClick={() => setActiveTab(tab)}>{tab}{tab === 'Headers' && <span>2</span>}</button>)}</div><div className="parameters"><div className="table-heading"><span>{activeTab === 'Params' ? 'Query parameters' : activeTab}</span><button className="text-button"><Plus size={13}/>Add {activeTab === 'Params' ? 'parameter' : 'item'}</button></div><div className="parameter-row"><input type="checkbox" defaultChecked/><input placeholder="Key"/><input placeholder="Value"/><button className="remove-button">×</button></div><div className="parameter-row muted-row"><input type="checkbox"/><input placeholder="Key"/><input placeholder="Value"/><button className="remove-button">×</button></div></div><div className="response-header"><div><span className="eyebrow">Response</span><span className={`response-meta ${sent ? 'success' : ''}`}>{sent ? '200 OK · 184 ms' : 'Ready to send'}</span></div><button className="quiet-button" onClick={() => setSent(false)}>Clear</button></div><div className="response-viewer">{sent ? <pre className="json-response">{'{\n  "data": [\n    { "id": 1, "name": "Ada Lovelace" },\n    { "id": 2, "name": "Grace Hopper" }\n  ],\n  "total": 2\n}'}</pre> : <div className="empty-response"><span className="response-symbol">→</span><strong>Send a request to inspect the response</strong><span>Status, headers, timing, and body will appear here.</span></div>}</div></section></main>
      <aside className="ai-panel"><div className="panel-heading"><div><span className="eyebrow">Workspace tool</span><h2><Bot size={16}/>AI assistant</h2></div><button className="icon-button"><X size={16}/></button></div><div className="ai-context">Current request<br/><strong>GET /users</strong></div><div className="suggestions"><button>Explain this request</button><button>Add authentication</button><button>Generate response tests</button></div><div className="ai-footer"><input placeholder="Ask about this request…"/><button className="send-ai"><Send size={14}/></button></div></aside>
    </div></div>
}

function Landing({ onDevelop, onLogin, onSignup }: { onDevelop: () => void; onLogin: () => void; onSignup: () => void }) {
  useEffect(() => { if (localStorage.getItem('api_studio_access_token')) onDevelop() }, [onDevelop])
  useEffect(() => { const keepVisibleAtTop = () => { if (window.scrollY < 80) document.querySelector('.landing-nav')?.classList.remove('nav-idle') }; keepVisibleAtTop(); window.addEventListener('scroll', keepVisibleAtTop, { passive: true }); return () => window.removeEventListener('scroll', keepVisibleAtTop) }, [])
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target) } }), { threshold: .1, rootMargin: '0px 0px -8% 0px' }); document.querySelectorAll('[data-reveal]').forEach(node => observer.observe(node)); const login = document.querySelector('.landing-actions .quiet-button'); const signup = document.querySelector('.landing-actions .outline-button'); login?.addEventListener('click', onLogin); signup?.addEventListener('click', onSignup); return () => { observer.disconnect(); login?.removeEventListener('click', onLogin); signup?.removeEventListener('click', onSignup) } }, [onLogin, onSignup])
  useEffect(() => { let timer: number | undefined; const nav = () => document.querySelector('.landing-nav'); const show = () => { nav()?.classList.remove('nav-idle'); window.clearTimeout(timer); if (window.scrollY > 80) timer = window.setTimeout(() => { if (window.scrollY > 80) nav()?.classList.add('nav-idle') }, 3000) }; window.addEventListener('scroll', show, { passive: true }); window.addEventListener('mousemove', show, { passive: true }); show(); return () => { window.removeEventListener('scroll', show); window.removeEventListener('mousemove', show); window.clearTimeout(timer) } }, [])
  const navigate = (event: MouseEvent<HTMLAnchorElement>, id: string) => { event.preventDefault(); const target = document.getElementById(id); target?.scrollIntoView({ behavior: 'smooth', block: 'start' }); target?.classList.remove('nav-focus'); window.setTimeout(() => target?.classList.add('nav-focus'), 350) }
  return <div className="landing"><header className="landing-nav"><button className="brand" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}><span className="brand-mark">A</span><span>API Studio</span><span className="brand-ai">AI</span></button><nav className="landing-links"><a href="#product" onClick={e => navigate(e, 'product')}>Product</a><a href="#workflow" onClick={e => navigate(e, 'workflow')}>Workflow</a><a href="#compare" onClick={e => navigate(e, 'compare')}>Compare</a><a href="#security" onClick={e => navigate(e, 'security')}>Security</a></nav><div className="landing-actions"><button className="quiet-button">Log in</button><button className="outline-button" onClick={onDevelop}>Sign up free <ArrowRight size={14}/></button></div><button className="mobile-menu"><Menu size={18}/></button></header>
    <main><section className="hero"><div className="hero-copy"><div className="status-line"><span></span>Built for people who build with APIs</div><h1>Make every API request<br/><em>feel understandable.</em></h1><p>Build, inspect, and improve APIs in one focused workspace. API Studio AI brings requests, environments, responses, and intelligent assistance together without getting in your way.</p><div className="hero-actions"><button className="primary-button" onClick={onDevelop}>Start building free <ArrowRight size={15}/></button><button className="quiet-button hero-secondary" onClick={onDevelop}>Explore the workspace <span>↗</span></button></div><div className="hero-note"><Check size={14}/> No credit card <span>·</span> Local-first workflow <span>·</span> Open formats</div></div><div className="hero-preview"><div className="preview-top"><span className="window-dots">● ● ●</span><span>api-studio / workspace</span><span className="preview-live">● Live</span></div><div className="preview-body"><div className="preview-rail"><b>A</b><span>▱</span><span>◇</span><span>◷</span><span>✦</span></div><div className="preview-main"><div className="preview-tab">Untitled request <span>×</span></div><div className="preview-request"><strong>GET</strong><span>api.example.com/users</span><button>Send</button></div><div className="preview-tabs"><span className="selected">Params</span><span>Authorization</span><span>Headers <i>2</i></span><span>Body</span></div><div className="preview-lines"><div><span>□</span><label>page</label><code>1</code></div><div><span>□</span><label>limit</label><code>20</code></div></div><div className="preview-response"><small>RESPONSE <b>200 OK · 184 ms</b></small><pre>{'{\n  "data": [\n    { "id": 1, "name": "Ada" },\n    { "id": 2, "name": "Grace" }\n  ]\n}'}</pre></div></div><div className="preview-ai"><small>WORKSPACE TOOL</small><strong><Sparkles size={13}/> AI assistant</strong><p>Explain this response</p><p>Add authentication</p><p>Generate tests</p></div></div></div></section>
      <section className="proof-row"><span className="method-get">Designed for serious API work</span><span className="method-post">Request intelligence</span><span className="method-put">Environment control</span><span className="method-delete">Clear responses</span></section>
      <section className="section-intro reveal" data-reveal id="product"><span className="eyebrow">One workspace, less friction</span><h2>Everything you need between<br/><span className="accent-word">an idea</span> and a reliable request.</h2><p>Keep the work close to the request. Every part of API Studio AI exists to help you understand what you are sending and what comes back.</p></section>
      <section className="feature-grid reveal" data-reveal><article><span className="feature-icon"><Terminal size={17}/></span><h3>Build without context switching</h3><p>Compose requests, manage headers, and work with variables where the request lives.</p><a href="#workflow">Request builder <ArrowRight size={14}/></a></article><article><span className="feature-index">02</span><span className="feature-icon"><Sparkles size={17}/></span><h3>AI that stays in context</h3><p>Ask for an explanation, a change, or a test. Preview the result before anything changes.</p><a href="#workflow">See the workflow <ArrowRight size={14}/></a></article><article><span className="feature-index">03</span><span className="feature-icon"><ShieldCheck size={17}/></span><h3>Confidence in every response</h3><p>Inspect status, timing, headers, cookies, and body content in one readable surface.</p><a href="#security">Read about control <ArrowRight size={14}/></a></article></section>
      <section className="workflow-section reveal" data-reveal id="workflow"><div><span className="eyebrow">A calmer way to work</span><h2>From first request<br/>to understood response.</h2><p>Start with a URL, import an existing definition, or let the assistant draft a request. API Studio keeps the workflow visible from beginning to end.</p><button className="outline-button" onClick={onDevelop}>Open Develop <ArrowRight size={14}/></button></div><ol><li><b>01</b><div><strong>Compose</strong><span>Set the method, URL, headers, and environment.</span></div></li><li><b>02</b><div><strong>Execute</strong><span>Send with clear status and long-running feedback.</span></div></li><li><b>03</b><div><strong>Understand</strong><span>Inspect the response or ask AI to explain it.</span></div></li></ol></section>
      <section className="compare-section reveal" data-reveal id="compare"><div className="compare-heading"><span className="eyebrow">Built for teams that ship</span><h2>A focused alternative<br/>to scattered API work.</h2><p>Use one workspace for the daily loop: draft, execute, inspect, and improve. Keep enterprise needs visible without turning the work into a maze of tools.</p></div><div className="comparison"><div className="comparison-head"><span>Capability</span><strong>API Studio AI</strong><span>Typical API workflow</span></div><div><span>Request building</span><b><Check size={15}/> One persistent workbench</b><span>Switch between tools</span></div><div><span>AI assistance</span><b><Check size={15}/> Contextual and preview-first</b><span>Separate chat or opaque automation</span></div><div><span>Team readiness</span><b><Check size={15}/> Environments, history, collections</b><span>Manual coordination</span></div><div><span>Response understanding</span><b><Check size={15}/> Status, body, headers, timing</b><span>Raw output and guesswork</span></div></div></section>
      <section className="import-section"><div><span className="eyebrow">Bring your work with you</span><h2>Start where your API already is.</h2></div><div className="import-options"><div><Upload size={17}/><strong>Import a collection</strong><span>Use an existing API client export.</span></div><div><Code2 size={17}/><strong>Open an API definition</strong><span>Work from OpenAPI or a URL.</span></div><div><Terminal size={17}/><strong>Paste a cURL command</strong><span>Turn a command into a request.</span></div></div></section>
      <section className="use-cases reveal" data-reveal><div className="use-cases-intro"><span className="eyebrow">Made for the whole API lifecycle</span><h2>One tool for the moments that slow teams down.</h2><p>API Studio AI gives every role a clear place to work, without asking the team to learn a different workflow for every stage.</p></div><div className="use-case-list"><article><span>01</span><div><h3>For backend engineers</h3><p>Move from endpoint idea to a reproducible request quickly. Keep variables, headers, and response checks beside the work.</p><a href="#workflow">Build and debug <ArrowRight size={14}/></a></div></article><article><span>02</span><div><h3>For platform teams</h3><p>Make environments easier to understand, keep collections organized, and give teams a shared history of what was actually executed.</p><a href="#security">Create team confidence <ArrowRight size={14}/></a></div></article><article><span>03</span><div><h3>For QA and integration teams</h3><p>Replay real requests, inspect the full response, and turn useful examples into tests without copying data between tools.</p><a href="#product">Inspect every detail <ArrowRight size={14}/></a></div></article></div></section>
      <section className="capability-band reveal" data-reveal><div><span className="eyebrow">Clarity at every layer</span><h2>Small details add up to faster decisions.</h2></div><div className="capability-copy"><p><strong>Live validation</strong><br/>Catch malformed URLs, missing variables, and incomplete request data before execution.</p><p><strong>Response intelligence</strong><br/>Read status, timing, headers, cookies, and formatted bodies without losing the request context.</p><p><strong>Safe assistance</strong><br/>AI explains first, previews changes, and keeps destructive actions behind confirmation.</p></div></section>
      <section className="plans-section reveal" data-reveal><div><span className="eyebrow">Start small. Grow deliberately.</span><h2>Useful on day one.<br/>Ready for the team.</h2><p>Begin with the complete request workflow. Add shared environments, collections, and team controls as your API surface grows.</p></div><div className="plan"><div><span className="plan-label">Early access</span><h3>Free while we build</h3><p>Everything needed to build and understand requests in one focused workspace.</p></div><ul><li><Check size={15}/> Request builder and response viewer</li><li><Check size={15}/> Collections and environments</li><li><Check size={15}/> Contextual AI assistance</li><li><Check size={15}/> Import from common formats</li></ul><button className="primary-button" onClick={onDevelop}>Create your workspace <ArrowRight size={15}/></button></div></section>
      <section className="final-cta" id="security"><span className="eyebrow">Your next request starts here</span><h2>Make the work clearer.</h2><button className="primary-button" onClick={onDevelop}>Create your workspace <ArrowRight size={15}/></button></section></main><footer><span className="brand"><span className="brand-mark">A</span><span>API Studio</span><span className="brand-ai">AI</span></span><span>Focused tools for API work.</span><span>© 2026 API Studio AI</span></footer></div>
}

const Workspace = DashboardConnected

function LegacyAuth({ mode, onBack, onSwitch, onSuccess }: { mode: 'login' | 'signup'; onBack: () => void; onSwitch: (mode: 'login' | 'signup') => void; onSuccess?: () => void }) {
  const signup = mode === 'signup'; const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [username, setUsername] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: Event) => { event.preventDefault(); const fields = Array.from(document.querySelectorAll('.auth-form input:not([type="checkbox"])')) as HTMLInputElement[]; const formEmail = signup ? fields[1]?.value : fields[0]?.value; const formPassword = signup ? fields[2]?.value : fields[1]?.value; const formUsername = signup ? fields[0]?.value : ''; setLoading(true); setError(''); try { const result = signup ? await api.auth.register({ email: formEmail || '', username: formUsername || '', password: formPassword || '' }) : await api.auth.login({ email: formEmail || '', password: formPassword || '' }); if (!signup) { const tokens = result as { access_token: string; refresh_token: string }; localStorage.setItem('api_studio_access_token', tokens.access_token); localStorage.setItem('api_studio_refresh_token', tokens.refresh_token) } onSuccess?.() } catch (err) { setError(err instanceof Error ? err.message : 'Unable to complete authentication.') } finally { setLoading(false) } }
  useEffect(() => { const form = document.querySelector('.auth-form form'); form?.addEventListener('submit', submit); return () => form?.removeEventListener('submit', submit) }, [submit])
  return <div className="auth-page"><section className="auth-context"><button className="brand auth-brand" onClick={onBack}><span className="brand-mark">A</span><span>API Studio</span><span className="brand-ai">AI</span></button><div className="auth-message"><span className="eyebrow">A clearer API workflow</span><h1>{signup ? 'Start with the request.' : 'Welcome back to the workbench.'}</h1><p>{signup ? 'Build, inspect, and understand every request in one focused workspace.' : 'Your collections, environments, and request history are ready when you are.'}</p></div><div className="auth-api-map"><div className="auth-endpoint endpoint-one"><b>GET</b><span>/users</span></div><div className="auth-endpoint endpoint-two"><b>POST</b><span>/collections</span></div><div className="auth-endpoint endpoint-three"><b>200</b><span>response</span></div><i className="auth-path path-one"/><i className="auth-path path-two"/></div><button className="auth-back" onClick={onBack}>← Back to overview</button></section><section className="auth-form-side"><div className="auth-form"><div className="auth-form-heading"><span className="eyebrow">{signup ? 'Create account' : 'Sign in'}</span><h2>{signup ? 'Build with clarity.' : 'Good to see you.'}</h2><p>{signup ? 'Create your workspace and make your next request easier to understand.' : 'Continue to your API workspace.'}</p></div><form onSubmit={e => e.preventDefault()}>{signup && <label>Full name<input type="text" placeholder="Ada Lovelace" /></label>}<label>Work email<input type="email" placeholder="you@company.com" /></label><label>Password<input type="password" placeholder="At least 8 characters" /></label>{signup && <label className="check-label"><input type="checkbox"/> <span>I agree to the terms and privacy policy.</span></label>}<button className="primary-button auth-submit">{signup ? 'Create workspace' : 'Log in'} <ArrowRight size={15}/></button></form>{!signup && <button className="forgot">Forgot your password?</button>}<div className="auth-switch">{signup ? 'Already have an account?' : 'New to API Studio AI?'} <button onClick={() => onSwitch(signup ? 'login' : 'signup')}>{signup ? 'Log in' : 'Sign up free'}</button></div></div></section></div>
}

function App() { const [page, setPage] = useState<'landing' | 'develop' | 'login' | 'signup'>('landing'); if (page === 'login' || page === 'signup') return <Auth mode={page} onBack={() => setPage('landing')} onSwitch={setPage} />; return page === 'landing' ? <Landing onDevelop={() => setPage('develop')} onLogin={() => setPage('login')} onSignup={() => setPage('signup')} /> : <><div className="develop-bar"><button className="brand" onClick={() => setPage('landing')}><span className="brand-mark">A</span><span>API Studio</span><span className="brand-ai">AI</span></button><span className="develop-label">Develop</span><button className="quiet-button" onClick={() => setPage('landing')}>← Back to overview</button></div><Workspace /></> }
createRoot(document.getElementById('root')!).render(<App />)
